// <auto-generated />
using System;
using InvestmentOrders.Infrastructure.Orders.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentOrders.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InvestmentOrders.Domain.Entities.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoActivoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoActivoId");

                    b.ToTable("Activos", (string)null);
                });

            modelBuilder.Entity("InvestmentOrders.Domain.Entities.EstadoOrden", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadoOrdenes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Descripcion = "En Proceso"
                        },
                        new
                        {
                            Id = 1,
                            Descripcion = "Ejecutada"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cancelada"
                        });
                });

            modelBuilder.Entity("InvestmentOrders.Domain.Entities.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuentaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreActivo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<char>("Operacion")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ordenes", (string)null);
                });

            modelBuilder.Entity("InvestmentOrders.Domain.Entities.TipoActivo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposActivo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acción"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Bono"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "FCI"
                        });
                });

            modelBuilder.Entity("InvestmentOrders.Domain.Entities.Activo", b =>
                {
                    b.HasOne("InvestmentOrders.Domain.Entities.TipoActivo", "TipoActivo")
                        .WithMany()
                        .HasForeignKey("TipoActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoActivo");
                });
#pragma warning restore 612, 618
        }
    }
}
